@rootURL = http://localhost:5091

GET {{rootURL}}/api/todos
Accept: application/json

###
POST {{rootURL}}/api/todos
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6Im5ld3VzZXIiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJVc2VyIiwiZXhwIjoxNzYyNjE4MzIxLCJpc3MiOiJNeUFwaSIsImF1ZCI6Ik15QW5ndWxhckFwcCJ9.e9I8ZufEcvBYDL34UbMTFuhToyIrq9IGE3StPxnzkg8
{
  "title": "New Todo Task"
}
###
PUT {{rootURL}}/api/todos/4
Accept: application/json
Content-Type: application/json
{
  "id": 4,
  "title": "Updated Todo Task",
  "isCompleted": true
}
###
DELETE {{rootURL}}/api/todos/4
Accept: application/json
###
POST {{rootURL}}/api/auth/login
Accept: application/json
Content-Type: application/json
{
  "username": "newuser",
  "password": "newpassword"
}
###
POST {{rootURL}}/api/auth/register
Accept: application/json
Content-Type: application/json
{
  "username": "newuser",
  "password": "newpassword",
  "confirmPassword": "newpassword",
  "email": "newuser@email.test"
}
###
GET {{rootURL}}/api/todos/me
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6Im5ld3VzZXIiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJVc2VyIiwiZXhwIjoxNzYyNjE4MzIxLCJpc3MiOiJNeUFwaSIsImF1ZCI6Ik15QW5ndWxhckFwcCJ9.e9I8ZufEcvBYDL34UbMTFuhToyIrq9IGE3StPxnzkg8